import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ClassAvatar, Icon } from './Dashboard';
import { inBucket } from './model';
import type { Bucket, DashboardClass, DemoTask } from './model';
import { dateRange, demoTaskDetails, matchesTask, presetFilters, relativeDate, taskStatus } from './task-list-model';
import type { TaskFilters, TaskStatus } from './task-list-model';
import './class-task-list.css';
import { ProgressDisplay } from '../test-controls/ProgressDisplay';
import '../test-controls/report-controls.css';
const typeOptions=['Adaptive task','Custom task','Test','Lesson','Worksheet','Custom worksheet','Discovery check-in','Topic readiness check-in','Revision task'];
const typeIcon=(type:string)=>type==='Test'?'test':type==='Adaptive task'?'adaptive':type==='Topic readiness check-in'?'readiness':type.includes('check-in')?'checkin':type==='Lesson'?'lesson':type.toLowerCase().includes('worksheet')?'worksheet':'custom';
const labelType=(type:string)=>type==='Custom task'?'Custom':type==='Adaptive task'?'Adaptive':type==='Topic readiness check-in'?'Readiness check':type;
const prettyDate=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'});
type Props={onFiltersChange?:(filters:TaskFilters)=>void;showClassChrome?:boolean;studentResult?:(taskId:string,name:string,grades:boolean)=>string;item:DashboardClass;initialPreset?:Bucket;initialFilters?:TaskFilters;onReport:(task:DemoTask)=>void;onAssign:()=>void;onClose?:()=>void;onSection?:(section:string)=>void;fullPage?:boolean};
export default function ClassTaskList({item,initialPreset='All',initialFilters,onReport,onAssign,onClose,onSection,fullPage=false,studentResult,showClassChrome=true,onFiltersChange}:Props){
 const [filters,setFilters]=useState(()=>initialFilters??presetFilters(initialPreset)),[popover,setPopover]=useState<string|null>(null),[view,setView]=useState('Tasks'),[sort,setSort]=useState('due'),[reverse,setReverse]=useState(false),[dateDraft,setDateDraft]=useState({date:'All dates',from:'',to:''});
 useEffect(()=>{onFiltersChange?.(filters)},[filters,onFiltersChange]);
 const [now]=useState(()=>Date.now());
 const root=useRef<HTMLDivElement>(null);
 const [popupPosition,setPopupPosition]=useState({left:0,top:0,maxHeight:500});
 useEffect(()=>{const scroll=(e:Event)=>{if(!(e.target as Element)?.closest?.('.task-filter-popup'))setPopover(null)};window.addEventListener('resize',scroll);document.addEventListener('scroll',scroll,true);const dismiss=(e:MouseEvent)=>{if(!(e.target as Element).closest('.task-filter'))setPopover(null)};document.addEventListener('mousedown',dismiss);return()=>{document.removeEventListener('mousedown',dismiss);window.removeEventListener('resize',scroll);document.removeEventListener('scroll',scroll,true)}},[]);
 const change=(next:Partial<TaskFilters>)=>setFilters(f=>({...f,...next,preset:null}));
 const preset=(b:Bucket)=>{setFilters(presetFilters(b));setPopover(null)};
 const toggle=(field:'statuses'|'types',value:string)=>change({[field]:filters[field].includes(value as never)?filters[field].filter(v=>v!==value):[...filters[field],value]});
 const openFilter=(name:string,button:HTMLButtonElement)=>{const rect=button.getBoundingClientRect();setPopupPosition({left:Math.max(8,Math.min(rect.left,window.innerWidth-(name==='Dates'?Math.min(614,window.innerWidth-32):280)-16)),top:rect.bottom+5,maxHeight:window.innerHeight-rect.bottom-16});if(name==='Dates')setDateDraft({date:filters.date,from:filters.from,to:filters.to});setPopover(popover===name?null:name)};
 const tasks=item.tasks.filter(t=>matchesTask(t,filters)).sort((a,b)=>{const d=sort==='name'?a.title.localeCompare(b.title):sort==='type'?a.type.localeCompare(b.type):sort==='result'?(a.result??-1)-(b.result??-1):sort==='participation'?a.participation-b.participation:sort==='progress'?demoTaskDetails(a,item).progress-demoTaskDetails(b,item).progress:a.dueIn-b.dueIn;return reverse?-d:d});
 const filterButton=(name:string,label:string,icon:string,children:React.ReactNode)=><div className="task-filter"><button className="task-filter-trigger" aria-label={`${name}: ${label}`} aria-expanded={popover===name} onClick={e=>openFilter(name,e.currentTarget)}><Icon name={icon}/><span>{label}</span><Icon name={popover===name?'filter':'down'}/></button>{popover===name&&<div className={`task-filter-popup ${name==='Dates'?'task-date-popup':''}`} style={popupPosition} role="dialog" aria-label={`${name} filter`}><h3>{name==='Presets'?'Task filter presets':name==='Dates'?'Due date range':name}</h3>{children}</div>}</div>;
 const sortHeading=(label:string,key:string)=><button onClick={()=>{setSort(key);setReverse(sort===key?!reverse:false)}}>{label}<Icon name="sort-small"/></button>;
 const filteredCount=tasks.length;
 return <div className="class-task-list" ref={root} onKeyDown={e=>{if(e.key==='Escape'&&popover){e.stopPropagation();setPopover(null);(root.current?.querySelector('[aria-expanded="true"]') as HTMLElement)?.focus()}}}>
 {showClassChrome&&<><header className="class-task-header"><ClassAvatar item={item}/><div><h2 style={{color:['#ae38ff','#ff32a6','#f46b00','#007e73','#0061ff','#8e3d9c'][item.avatar]}}>{item.name}</h2><div className="class-task-meta"><span><Icon name="calendar"/>2026</span><span><Icon name="year"/>{item.year}</span><span><Icon name="students"/>{item.students.length}</span><span><Icon name="teacher"/>{item.teacher}</span></div></div><div className="class-task-actions"><button className="dash-outline" onClick={()=>onSection?.('students')}><Icon name="edit"/>Class settings</button>{!fullPage&&<Link className="task-full-page" to={`/classes/${item.id}/tasks?preset=${encodeURIComponent(filters.preset??'All')}&filters=${encodeURIComponent(JSON.stringify(filters))}`}>View full page <Icon name="chevron"/></Link>}{onClose&&<button className="dash-close" aria-label="Close dashboard sheet" onClick={onClose}><i/></button>}</div></header>
 <nav className="class-task-nav" aria-label="Class sections">{[['Insights','health'],['Planner','calendar'],['Activity','activity'],['Textbook','book'],['Tasks','task-empty'],['Skills','skills']].map(([name,icon])=><button key={name} aria-current={name==='Tasks'?'page':undefined} onClick={()=>name==='Tasks'?setView('Tasks'):onSection?.(name.toLowerCase())}><Icon name={icon}/>{name}</button>)}</nav></>}
 <div className="class-task-toolbar"><div className="task-view-toggle" aria-label="Task table view">{['Tasks','Students','Grades'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v}</button>)}</div>
 {filterButton('Presets',filters.preset&&filters.preset!=='All'?filters.preset:'Presets','presets',<>{(['Recent','Due soon','Active'] as Bucket[]).map(b=><button className={`task-preset-option ${filters.preset===b?'selected':''}`} key={b} onClick={()=>preset(b)}><Icon name={b==='Recent'?'recent':b==='Due soon'?'due':'active'}/><span>{b} ({item.tasks.filter(t=>inBucket(t,b)).length})<small>{b==='Recent'?'Hit due date in the last 7 days':b==='Due soon'?'Due today or in the next 2 days':'Open to students'}</small></span><span aria-hidden="true">{filters.preset===b?'☑':'□'}</span></button>)}<button className="task-clear" onClick={()=>preset('All')}>Clear preset and filters</button></>)}
 {filterButton('Dates',filters.date,'date',<><div className="task-date-shortcuts">{['This week','Last 7 days','Last 14 days','Last 30 days','Next 2 days','All dates','Custom'].map(d=><button key={d} aria-pressed={dateDraft.date===d} onClick={()=>setDateDraft({date:d,...(d==='Custom'?{from:dateDraft.from,to:dateDraft.to}:dateRange(d))})}>{d}</button>)}</div><DateCalendar from={dateDraft.from} to={dateDraft.to} onChange={(from,to)=>setDateDraft({date:'Custom',from,to})}/><div className="task-date-inputs"><label>From<input type="date" value={dateDraft.from} onChange={e=>setDateDraft({...dateDraft,date:'Custom',from:e.target.value})}/></label><label>To<input type="date" min={dateDraft.from} value={dateDraft.to} onChange={e=>setDateDraft({...dateDraft,date:'Custom',to:e.target.value})}/></label></div><div className="task-popup-footer"><span>{dateDraft.date==='Custom'?`${dateDraft.from||'Any start'} – ${dateDraft.to||'Any end'}`:dateDraft.date}</span><button className="dash-primary" disabled={!!(dateDraft.from&&dateDraft.to&&dateDraft.from>dateDraft.to)} onClick={()=>{change(dateDraft);setPopover(null)}}>Save</button></div></>)}
 {filterButton('Task type',filters.types.length===1?labelType(filters.types[0]):filters.types.length?`Multiple (${filters.types.length})`:'Task type','task-empty',<>{typeOptions.map(t=><label className="task-filter-option" key={t}><Icon name={typeIcon(t)}/><span>{t==='Custom task'?'Custom (Learning)':t==='Test'?'Custom (Test)':labelType(t)}</span><input type="checkbox" checked={filters.types.includes(t)} onChange={()=>toggle('types',t)}/></label>)}<button className="task-clear" onClick={()=>change({types:[]})}>Clear</button></>)}
 {filterButton('Assigned to',filters.assigned||'Assigned to','class-filter',<>{['Whole class','Individual students'].map(a=><label className="task-filter-option" key={a}><span>{a==='Whole class'?item.name:a}</span><input type="radio" name="assigned" checked={filters.assigned===a} onChange={()=>change({assigned:a})}/></label>)}<button className="task-clear" onClick={()=>change({assigned:''})}>Clear</button></>)}
 {filterButton('Status',filters.statuses.length===1?filters.statuses[0]:filters.statuses.length?`Multiple (${filters.statuses.length})`:'All statuses','status',<>{(['Active','In extension','Closed'] as TaskStatus[]).map(s=><label className="task-filter-option" key={s}><Icon name={s==='Active'?'active':s==='Closed'?'recent':'due'}/><span>{s}</span><input type="checkbox" checked={filters.statuses.includes(s)} onChange={()=>toggle('statuses',s)}/></label>)}<button className="task-clear" onClick={()=>change({statuses:[]})}>Clear</button></>)}
 <button className="dash-outline task-assign" onClick={onAssign}><Icon name="add"/>Assign task</button></div>
 <div className="task-list-search"><input aria-label="Search class tasks" placeholder="Search tasks" value={filters.query} onChange={e=>change({query:e.target.value})}/><span role="status">{filteredCount} of {item.tasks.length} tasks</span><button onClick={()=>preset('All')}>Clear filters</button></div>
 <div className="class-task-table-scroll">{view==='Tasks'?<table className="class-task-table"><thead><tr><th>{sortHeading(`Tasks (${tasks.length})`,'name')}</th><th>{sortHeading('Task type','type')}</th><th>{sortHeading('Progress','progress')}</th><th>{sortHeading('Participation','participation')}</th><th>{sortHeading('Results','result')}</th><th>Revision</th><th>Time spent</th><th>Status</th><th>Task start</th><th>{sortHeading('Task due','due')}</th><th>Task expiry</th></tr></thead><tbody>{tasks.map(t=>{const d=demoTaskDetails(t,item),status=taskStatus(t);return <tr key={t.id}><td><button className="task-name" onClick={()=>onReport(t)}><TaskPictogram/><strong>{t.title}</strong></button></td><td><span className="task-type-chip"><Icon name={typeIcon(t.type)}/>{labelType(t.type)}</span></td><td><ProgressDisplay aggregate variant="01" custom={t.type!=='Test'} now={now} student={{id:0,name:t.title,group:item.name,mode:'Untimed',status:'In progress',progress:d.progress,remaining:0,version:1,start:d.start,due:d.due}}/></td><td><span className="task-participation"><Icon name="students"/>{t.participation} / {t.assignedCount??item.students.length}</span></td><td>{t.result===null?'—':<span className="task-result"><Icon name="recent"/>{t.result}%</span>}</td><td>—</td><td>{d.minutes===null?'—':`${d.minutes}m`}</td><td><span className={`task-status-chip ${status==='Closed'?'closed':status==='In extension'?'extension':'active'}`}><Icon name={status==='Closed'?'recent':status==='In extension'?'due':'active'}/>{status}</span>{status==='Active'&&t.dueIn<=2&&<small className="task-due-label">{t.dueIn===0?'Due today':t.dueIn===1?'Due tomorrow':'Due in 2 days'}</small>}</td><td>{prettyDate(d.start)}</td><td>{prettyDate(d.due)}</td><td>{prettyDate(d.expiry)}</td></tr>})}</tbody></table>:<table className="class-task-table"><thead><tr><th>Student</th>{tasks.map(t=><th key={t.id}><button onClick={()=>onReport(t)}>{t.title}</button></th>)}</tr></thead><tbody>{item.students.map((name,i)=><tr key={name}><td>{name}</td>{tasks.map(t=><td key={t.id}>{studentResult?studentResult(t.id,name,view==='Grades'):i>=t.participation?'Not started':view==='Grades'?(t.result===null?'Not marked':`${t.result}%`):t.completed?'Completed':'In progress'}</td>)}</tr>)}</tbody></table>}</div>
 {!tasks.length&&<div className="dash-empty"><h3>{item.tasks.length?'No tasks match these filters':'No tasks yet'}</h3><p>{item.tasks.length?'Try another preset or clear your filters.':'Assign a task to get this class started.'}</p><button className="dash-primary" onClick={()=>item.tasks.length?preset('All'):onAssign()}>{item.tasks.length?'Clear filters':'Assign task'}</button></div>}
 </div>
}
function TaskPictogram(){return <span className="task-pictogram" aria-hidden="true"><span><img className="question-back" src="/assets/dashboard/question-back.svg" alt=""/><img className="question-side" src="/assets/dashboard/question-side.svg" alt=""/><img className="question-front" src="/assets/dashboard/question-front.svg" alt=""/></span></span>}
function DateCalendar({from,to,onChange}:{from:string;to:string;onChange:(from:string,to:string)=>void}){
 const [month,setMonth]=useState(()=>{const d=from?new Date(`${from}T12:00:00`):new Date();return new Date(d.getFullYear(),d.getMonth(),1)});
 const next=new Date(month.getFullYear(),month.getMonth()+1,1);
 return <div className="task-calendar"><header><button aria-label="Previous month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><strong>{month.toLocaleDateString('en-AU',{month:'long',year:'numeric'})}<span className="calendar-second"> – {next.toLocaleDateString('en-AU',{month:'long',year:'numeric'})}</span></strong><button aria-label="Next month" onClick={()=>setMonth(next)}>›</button></header><div className="task-calendar-months">{[month,next].map((m,index)=><div key={m.toISOString()} className={`task-calendar-grid ${index?'calendar-second':''}`}>{['M','T','W','T','F','S','S'].map((d,i)=><b key={i}>{d}</b>)}{Array.from({length:(m.getDay()+6)%7},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:new Date(m.getFullYear(),m.getMonth()+1,0).getDate()},(_,i)=>{const day=`${m.getFullYear()}-${String(m.getMonth()+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return <button key={day} aria-label={prettyDate(day)} aria-pressed={day===from||day===to} className={from&&day>=from&&day<=(to||from)?'in-range':''} onClick={()=>!from||to||day<from?onChange(day,''):onChange(from,day)}>{i+1}</button>})}</div>)}</div><small>Choose a start date, then an end date. Today: {prettyDate(relativeDate(0))}</small></div>
}
