import { useEffect, useId, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ClassAvatar, Icon } from './Dashboard';
import type { Screen } from './Dashboard';
import { inBucket, studentNames, taskTypes, topics } from './model';
import type { Bucket, DashboardClass, DemoTask } from './model';
import { StudentAvatar } from '../test-controls/StudentAvatar';
type Props={screen:Screen;classes:DashboardClass[];onClose:()=>void;onOpen:(s:Screen)=>void;onUpdate:(id:string,c:Partial<DashboardClass>)=>void;onAdd:(c:DashboardClass)=>void;onNotice:(s:string)=>void};
export default function DashboardSheet(p:Props){
 const {screen,onClose}=p,ref=useRef<HTMLDivElement>(null),heading=useId();
 const c=p.classes.find(c=>c.id===screen.classId);
 const [query,setQuery]=useState(''),[bucket,setBucket]=useState<Bucket>(screen.bucket??'All'),[year,setYear]=useState('All'),[owner,setOwner]=useState('All');
 const titles={tasks:'Tasks',report:'Task report',textbook:'Textbook',focus:'Set topic focus',assign:'Assign a task',directory:'Class directory',health:'Class performance',recommendations:'Recommendations',students:'Students',add:'Add class',guide:screen.guide??'Get to know Mathspace'};
 useEffect(()=>{const prev=document.activeElement as HTMLElement;ref.current?.focus();return()=>{if(prev?.isConnected)prev.focus()}},[]);
 const open=(kind:Screen['kind'],extra:Partial<Screen>={})=>p.onOpen({kind,classId:c?.id,...extra});
 const filtered=p.classes.filter(c=>(year==='All'||String(c.year)===year)&&(owner==='All'||c.teacher===owner)&&`${c.name} ${c.teacher}`.toLowerCase().includes(query.toLowerCase()));
 return createPortal(<div className="dash-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={`dash-sheet ${['focus','assign','add'].includes(screen.kind)?'dash-sheet-narrow':''}`} role="dialog" aria-modal="true" aria-labelledby={heading} ref={ref} tabIndex={-1} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose()}if(e.key==='Tab'){const els=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select,textarea,summary')??[]).filter(e=>e.getClientRects().length);const first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><header className="dash-sheet-header"><h2 id={heading}>{titles[screen.kind]}</h2>{c&&<span><ClassAvatar item={c}/>{c.name}</span>}<button className="dash-close" aria-label="Close dashboard sheet" onClick={onClose}><i/></button></header><div className="dash-sheet-content">
 {(screen.kind==='directory'||screen.kind==='health')&&<><div className="dash-tabs"><button aria-pressed={screen.kind==='directory'} onClick={()=>open('directory',{classId:undefined})}>Directory</button><button aria-pressed={screen.kind==='health'} onClick={()=>open('health',{classId:undefined})}>Health</button></div><div className="dash-filterbar"><input aria-label="Search classes or teachers" placeholder="Search classes or teachers" value={query} onChange={e=>setQuery(e.target.value)}/><label>Year level <select value={year} onChange={e=>setYear(e.target.value)}><option>All</option>{[...new Set(p.classes.map(c=>c.year))].sort().map(y=><option key={y}>{y}</option>)}</select></label><label>Teacher <select value={owner} onChange={e=>setOwner(e.target.value)}><option>All</option>{[...new Set(p.classes.map(c=>c.teacher))].map(t=><option key={t}>{t}</option>)}</select></label><button className="dash-outline" onClick={()=>open('add',{classId:undefined})}>Add class</button></div><div className="dash-table-scroll"><table><thead><tr><th>Class</th><th>Teacher</th><th>Students</th><th>Year</th>{screen.kind==='directory'?<th>Textbook</th>:<><th>Textbook progress</th><th>Topic focus</th><th>Pacing</th><th>Task participation</th></>}</tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><button className="dash-class-table-link" onClick={()=>p.onOpen({kind:'tasks',classId:item.id})}><ClassAvatar item={item}/>{item.name}</button></td><td>{item.teacher}{item.teacher==='Sarah Mitchell'?' (you)':''}</td><td>{item.students.length}</td><td>{item.year}</td>{screen.kind==='directory'?<td>Australian Curriculum Year {item.year} · v9</td>:<><td>{item.completedTopics} / 16 topics</td><td>{item.focus?.topic??'Not set'}</td><td><span className={`dash-pace ${item.focus?.pace==='Behind'?'behind':''}`}>{item.focus?.pace??'Not available'}</span></td><td>{item.students.length&&item.tasks.length?`${Math.round(item.tasks.reduce((n,t)=>n+t.participation,0)/(item.tasks.length*item.students.length)*100)}%`:'No activity yet'}</td></>}</tr>)}</tbody></table></div>{!filtered.length&&<p className="dash-empty">No classes match these filters.</p>}<p className="dash-muted">Task participation is the average share of students who have started each task. Pacing is shown only where a topic focus has been set.</p></>}
 {screen.kind==='tasks'&&c&&<><div className="dash-filterbar"><div className="dash-tabs">{(['All','Recent','Due soon','Active'] as Bucket[]).map(b=><button aria-pressed={bucket===b} key={b} onClick={()=>setBucket(b)}>{b} ({c.tasks.filter(t=>inBucket(t,b)).length})</button>)}</div>{c.teacher==='Sarah Mitchell'&&<button className="dash-primary" onClick={()=>open('assign')}>Assign task</button>}<input placeholder="Search tasks" aria-label="Search tasks" value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="dash-muted">{bucket==='Recent'?'Completed in the last 7 days. Dismissing a dashboard card does not remove it here.':bucket==='Due soon'?'Active tasks due within the next 2 days.':bucket==='Active'?'All unfinished tasks, including those due soon.':'All tasks assigned to this class.'}</p><div className="dash-task-list">{c.tasks.filter(t=>inBucket(t,bucket)&&t.title.toLowerCase().includes(query.toLowerCase())).map(t=><button key={t.id} onClick={()=>open('report',{taskId:t.id})}><Icon name="task"/><span><strong>{t.title}</strong><small>{t.type} · {t.completed?'Completed recently':t.dueIn===1?'Due tomorrow':`Due in ${t.dueIn} days`}</small></span><span>{t.participation} / {c.students.length} started</span><b>{t.result===null?'In progress':`${t.result}%`}</b><Icon name="chevron"/></button>)}</div>{!c.tasks.filter(t=>inBucket(t,bucket)&&t.title.toLowerCase().includes(query.toLowerCase())).length&&<div className="dash-empty"><h3>No {bucket==='All'?'':bucket.toLowerCase()} tasks</h3><p>{c.students.length?'Assign a task to give this class something to work on.':'Add students before assigning your first task.'}</p><button className="dash-primary" onClick={()=>open(c.students.length?'assign':'students')}>{c.students.length?'Assign task':'Add students'}</button></div>}</>}
 {screen.kind==='report'&&c&&<TaskReport item={c} task={c.tasks.find(t=>t.id===screen.taskId)} onBack={()=>open('tasks')} onRecommendations={()=>open('recommendations')} />}
 {screen.kind==='textbook'&&c&&<><div className="dash-textbook-header"><Icon name="book"/><div><h3>Australian Curriculum Year {c.year}</h3><p>v9 2nd Edition · {c.completedTopics} of 16 topics covered</p></div><button className="dash-outline" onClick={()=>open('focus')}>Set topic focus</button></div><input className="dash-topic-search" placeholder="Search topics" aria-label="Search textbook topics" value={query} onChange={e=>setQuery(e.target.value)}/>{topics.filter(t=>t.toLowerCase().includes(query.toLowerCase())).map((topic,i)=><details className="dash-topic" key={topic} open={topic===c.focus?.topic||undefined}><summary><strong>{i+1}. {topic}</strong>{topic===c.focus?.topic&&<span className="dash-focus-tag">In focus</span>}<span>{i<c.completedTopics?'Covered':'Explore topic'}</span></summary><div><p>Explore worked examples, practise key skills, and check understanding.</p>{['Understanding the concept','Applying the method','Problem solving'].map((section,j)=><div className="dash-subtopic" key={section}><span>{i+1}.{String(j+1).padStart(2,'0')} · {section}</span><button onClick={()=>open('guide',{guide:`${topic}: ${section}`})}>Open lesson</button><button onClick={()=>open('assign',{guide:topic})}>Assign practice</button></div>)}<button className="dash-outline" onClick={()=>open('focus',{guide:topic})}>Focus on {topic}</button></div></details>)}{!topics.some(t=>t.toLowerCase().includes(query.toLowerCase()))&&<p>No topics match your search.</p>}</>}
 {screen.kind==='focus'&&c&&<FocusForm item={c} initialTopic={screen.guide} initialType={screen.taskType} onSave={focus=>{p.onUpdate(c.id,{focus});p.onNotice(`Topic focus updated for ${c.name}.`);onClose()}} onCancel={onClose}/>}
 {screen.kind==='assign'&&c&&<AssignForm item={c} initialTopic={screen.guide} initialType={screen.taskType} onSave={task=>{p.onUpdate(c.id,{tasks:[...c.tasks,task],history:true});p.onNotice(`“${task.title}” assigned to ${c.students.length} students in this prototype.`);open('tasks',{bucket:'Active'})}} onStudents={()=>open('students')}/>}
 {screen.kind==='students'&&c&&<StudentsForm item={c} onSave={students=>{p.onUpdate(c.id,{students});p.onNotice(`${students.length} students in ${c.name}.`)}}/>}
 {screen.kind==='add'&&<AddClass onSave={item=>{p.onAdd(item);p.onNotice(`${item.name} created. Add students to get started.`);p.onOpen({kind:'students',classId:item.id})}} existing={p.classes.map(c=>c.name)}/>}
 {screen.kind==='recommendations'&&c&&<Recommendations item={c} onOpen={open} onReward={names=>{p.onUpdate(c.id,{stickers:[...(c.stickers??[]),...names],celebrate:false});p.onNotice(`Stickers recorded for ${names.length} students in this prototype.`)}}/>}
 {screen.kind==='guide'&&<div className="dash-guide-content"><h3>{screen.guide??'Make the most of your dashboard'}</h3><p>Use your class cards to see what needs attention and take the next step.</p><ol><li><strong>Start with the class.</strong> Open its tasks, textbook, or student list without losing your place.</li><li><strong>Check understanding.</strong> Use a readiness check-in before teaching a topic, then review results to identify who needs support.</li><li><strong>Plan the next step.</strong> Set a topic focus, assign practice, or recognise students’ effort.</li></ol><p className="dash-muted">This is a local guide preview. The full lesson library and student application are outside this dashboard prototype.</p>{c&&<button className="dash-primary" onClick={()=>open('assign')}>Assign a task for {c.name}</button>}</div>}
 </div></section></div>,document.body)
}
function FocusForm({item,initialTopic,onSave,onCancel}:{item:DashboardClass;initialTopic?:string;initialType?:string;onSave:(focus:DashboardClass['focus'])=>void;onCancel:()=>void}){
 const [topic,setTopic]=useState(initialTopic??item.focus?.topic??''),[end,setEnd]=useState(item.focus?.end??''),[query,setQuery]=useState('');
 return <form onSubmit={e=>{e.preventDefault();onSave({topic,end,done:topic===item.focus?.topic?item.focus.done:0,total:5,pace:topic===item.focus?.topic?item.focus.pace:'On track'})}}><p>Choose the topic this class is currently working on.</p><p className="dash-muted">Australian Curriculum Year {item.year} · v9 2nd Edition</p><input aria-label="Search topic focus" placeholder="Search topics" value={query} onChange={e=>setQuery(e.target.value)}/><fieldset className="dash-topic-options"><legend>Topic</legend>{topics.filter(t=>t.toLowerCase().includes(query.toLowerCase())).map(t=><label key={t}><input type="radio" name="focus" value={t} checked={topic===t} onChange={()=>setTopic(t)}/>{t}</label>)}</fieldset><label className="dash-field">Expected finish date <small>Optional · helps plan pacing</small><input type="date" value={end} min={new Date().toISOString().slice(0,10)} onChange={e=>setEnd(e.target.value)}/></label><div className="dash-form-actions">{item.focus&&<button type="button" className="dash-text" onClick={()=>onSave(null)}>Clear focus</button>}<button type="button" onClick={onCancel}>Cancel</button><button className="dash-primary" disabled={!topic}>Set focus</button></div></form>
}
function AssignForm({item,initialTopic,initialType,onSave,onStudents}:{item:DashboardClass;initialTopic?:string;initialType?:string;onSave:(t:DemoTask)=>void;onStudents:()=>void}){
 const [type,setType]=useState(initialType??''),[title,setTitle]=useState(initialTopic?`${initialTopic} practice`:initialType??''),[days,setDays]=useState(7),[step,setStep]=useState(initialType?2:1);
 if(!item.students.length)return <div className="dash-empty"><h3>Add students first</h3><p>A task needs students to work on it.</p><button className="dash-primary" onClick={onStudents}>Add students</button></div>;
 return <form onSubmit={e=>{e.preventDefault();onSave({id:`assigned-${crypto.randomUUID()}`,title:title.trim(),type,completed:false,dueIn:days,participation:0,result:null})}}>{step===1?<><h3>What would you like this task to do?</h3>{taskTypes.map(group=><section className="dash-purpose" key={group.purpose}><h4>{group.purpose}</h4><p>{group.description}</p>{group.types.map(t=><button type="button" key={t} onClick={()=>{setType(t);setTitle(title||`${item.focus?.topic??'Mathematics'} · ${t.toLowerCase()}`);setStep(2)}}><Icon name="task"/>{t}<Icon name="chevron"/></button>)}</section>)}</>:<><button className="dash-text" type="button" onClick={()=>setStep(1)}>← Change task type</button><h3>{type}</h3><label className="dash-field">Task name<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="dash-field">Due in days<input type="number" min={1} max={60} required value={days} onChange={e=>setDays(Number(e.target.value))}/></label><p>{item.students.length} students · {item.name}</p><p className="dash-muted">This prototype creates a task in the class list. Question authoring and delivery to students are not connected.</p><div className="dash-form-actions"><button className="dash-primary" disabled={!title.trim()||days<1||days>60}>Assign to class</button></div></>}</form>
}
function StudentsForm({item,onSave}:{item:DashboardClass;onSave:(names:string[])=>void}){const [names,setNames]=useState('');return <><p>{item.students.length} students in {item.name}</p>{item.teacher==='Sarah Mitchell'&&<form onSubmit={e=>{e.preventDefault();const added=names.split('\n').map(n=>n.trim()).filter(Boolean);onSave([...new Set([...item.students,...added])]);setNames('')}}><label className="dash-field">Add students <small>One full name per line</small><textarea rows={3} value={names} onChange={e=>setNames(e.target.value)} placeholder={'Alex Morgan\nSam Taylor'}/></label><button className="dash-primary" disabled={!names.trim()}>Add students</button>{!item.students.length&&<button type="button" onClick={()=>onSave(studentNames.slice(0,24))}>Use demonstration roster</button>}</form>}<div className="dash-student-list">{item.students.map(name=><div key={name}><StudentAvatar name={name}/><strong>{name}</strong><span>{item.name}</span></div>)}</div></>}
function AddClass({onSave,existing}:{onSave:(c:DashboardClass)=>void;existing:string[]}){const [name,setName]=useState(''),[year,setYear]=useState(7);const duplicate=existing.some(n=>n.toLowerCase()===name.trim().toLowerCase());return <form onSubmit={e=>{e.preventDefault();if(duplicate)return;onSave({id:crypto.randomUUID(),name:name.trim(),year,students:[],teacher:'Sarah Mitchell',avatar:0,tasks:[],history:false,focus:null,completedTopics:0})}}><label className="dash-field">Class name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="8C Math"/></label>{duplicate&&<p role="alert">A class with this name already exists.</p>}<label className="dash-field">Year level<select value={year} onChange={e=>setYear(Number(e.target.value))}>{[7,8,9,10,11,12].map(n=><option key={n}>{n}</option>)}</select></label><p>Australian Curriculum · v9 2nd Edition</p><div className="dash-form-actions"><button className="dash-primary" disabled={!name.trim()||duplicate}>Create class</button></div></form>}
function TaskReport({item,task,onBack,onRecommendations}:{item:DashboardClass;task?:DemoTask;onBack:()=>void;onRecommendations:()=>void}){const [query,setQuery]=useState('');if(!task)return <p>Task not found. <button onClick={onBack}>Back to tasks</button></p>;return <><button className="dash-text" onClick={onBack}>← All tasks</button><h3>{task.title}</h3><p>{task.type} · {item.name} · {task.completed?'Complete':`Due in ${task.dueIn} days`}</p><div className="dash-report-stats"><div>Participation<strong>{task.participation} / {item.students.length}</strong></div><div>Average result<strong>{task.result===null?'Not marked yet':`${task.result}%`}</strong></div><button onClick={onRecommendations}>Review recommendations <Icon name="chevron"/></button></div><input aria-label="Search student report" placeholder="Search students" value={query} onChange={e=>setQuery(e.target.value)}/><div className="dash-table-scroll"><table><thead><tr><th>Student</th><th>Status</th><th>Result</th></tr></thead><tbody>{item.students.map((name,index)=>({name,index})).filter(s=>s.name.toLowerCase().includes(query.toLowerCase())).map(({name,index})=><tr key={name}><td><span className="dash-person"><StudentAvatar name={name}/>{name}</span></td><td>{index<task.participation?task.completed?'Completed':'In progress':'Not started'}</td><td>{index<task.participation&&task.result!==null?`${task.result}%`:'—'}</td></tr>)}</tbody></table></div><p className="dash-muted">Demonstration report. Explore detailed question responses in the Progressive results and Test controls prototypes.</p></>}
function Recommendations({item,onOpen,onReward}:{item:DashboardClass;onOpen:(kind:Screen['kind'],extra?:Partial<Screen>)=>void;onReward:(names:string[])=>void}){const [selected,setSelected]=useState<string[]>([]),[sent,setSent]=useState(false);const active=item.tasks.filter(t=>!t.completed),recent=item.tasks.find(t=>t.completed);return <div className="dash-recommendation-details">{!item.focus&&<article><img src="/assets/dashboard/focus.png" alt=""/><div><h3>Set a topic focus</h3><p>{item.name} has no topic selected. Set a focus to keep textbook progress and pacing in context.</p><button className="dash-primary" onClick={()=>onOpen('focus')}>Set focus</button></div></article>}{active.length>0&&<article><img src="/assets/dashboard/task.png" alt=""/><div><h3>Check participation before the next deadline</h3><p>{active[0].title}: {Math.max(0,item.students.length-active[0].participation)} of {item.students.length} students have not started. Review the report before deciding who needs a reminder or support.</p><button className="dash-primary" onClick={()=>onOpen('report',{taskId:active[0].id})}>Review students</button></div></article>}{!active.length&&<article><img src="/assets/dashboard/task.png" alt=""/><div><h3>{item.history?'Plan the next task':'Start with a readiness check-in'}</h3><p>{item.name} has no active tasks. Check understanding before choosing the next practice activity.</p><button className="dash-primary" onClick={()=>onOpen('assign')}>Assign a task</button></div></article>}{recent&&<article><img src="/assets/dashboard/stickers.png" alt=""/><div><h3>Recognise student progress</h3><p>{recent.participation} students completed “{recent.title}”. Review their work and choose who to recognise.</p><details><summary>Choose students ({selected.length} selected)</summary>{item.students.slice(0,recent.participation).map(name=><label className="dash-reward-option" key={name}><input type="checkbox" checked={selected.includes(name)} onChange={e=>setSelected(old=>e.target.checked?[...old,name]:old.filter(n=>n!==name))}/>{name}</label>)}</details><button className="dash-primary" disabled={!selected.length||sent} onClick={()=>{onReward(selected);setSent(true)}}>{sent?'Stickers recorded':'Send stickers'}</button>{sent&&<p role="status">Recorded in this prototype; no student messages were sent.</p>}</div></article>}</div>}
