export type Bucket='Recent'|'Due soon'|'Active'|'All';
export type DemoTask={id:string;title:string;type:string;completed:boolean;dueIn:number;participation:number;result:number|null;dismissed?:boolean;reviewed?:boolean};
export type Focus={topic:string;end:string;done:number;total:number;pace:'On track'|'Behind'|'Ahead'};
export type DashboardClass={id:string;name:string;year:number;students:string[];teacher:string;avatar:number;tasks:DemoTask[];history:boolean;focus:Focus|null;celebrate?:boolean;stickers?:string[];completedTopics:number};
export const studentNames=['Emma Johnson','Liam Martinez','Sophia Okonkwo','Noah Okafor','Olivia Petrov','Davis Mason','Amelia Chen','Lucas Wilson','Isla Patel','Ethan Nguyen','Mia Thompson','Oliver Lee','Ava Nguyen','Noah Patel','Emily Chen','Jack Williams','Zoe Brown','Leo Jones','Grace Wilson','Henry Taylor','Ella Martin','Oscar Li','Ruby Singh','Charlie Evans','Chloe Smith','Archie Davis','Sophie Kim','Max Wright'];
export const topics=['Whole numbers','Integers','Fractions','Decimals and percentages','Linear equations','Algebraic expressions','Measurement','Geometry','Statistics','Probability','Ratios and rates','Financial mathematics','Transformations','Pythagoras and trigonometry','Linear relationships','Problem solving'];
export const taskTypes=[{purpose:'Formative testing',description:'Uncover topic readiness and gaps',types:['Topic readiness check-in']},{purpose:'Learn',description:'Introduce new concepts with guided practice',types:['Adaptive task']},{purpose:'Practice',description:'Strengthen understanding',types:['Custom task','Revision task']},{purpose:'Summative testing',description:'Test their understanding',types:['Test']}];
function tasks(id:string,recent:number,active:number,due:number):DemoTask[]{return [...Array.from({length:recent},(_,i)=>({id:`${id}-r${i}`,title:['Converting decimals to percentages and vice versa','Equivalent fractions','Ordering rational numbers'][i%3],type:'Custom task',completed:true,dueIn:-1-i,participation:20+i,result:80+i*3})),...Array.from({length:active},(_,i)=>({id:`${id}-a${i}`,title:['Decimals and percentages practice','Linear equations practice','Fractions: applying your skills','Measurement revision','Algebra readiness'][i%5],type:i===4?'Topic readiness check-in':'Custom task',completed:false,dueIn:i<due?1+i:5+i,participation:5+i*2,result:null}))]}
export function seedDashboard():DashboardClass[]{return [
 {id:'dash-7a',name:'7A Math',year:7,students:studentNames.slice(0,28),teacher:'Sarah Mitchell',avatar:0,tasks:tasks('7a',1,1,1).map(t=>({...t,dismissed:true})),history:true,focus:{topic:topics[3],end:'',done:3,total:5,pace:'On track'},celebrate:true,completedTopics:6},
 {id:'dash-7b',name:'7B Math',year:7,students:studentNames.slice(0,25),teacher:'Sarah Mitchell',avatar:1,tasks:tasks('7b',3,0,0),history:true,focus:{topic:topics[2],end:'',done:2,total:5,pace:'Behind'},completedTopics:5},
 {id:'dash-7c',name:'7C Math',year:7,students:studentNames.slice(0,26),teacher:'Sarah Mitchell',avatar:2,tasks:tasks('7c',3,2,1),history:true,focus:{topic:topics[3],end:'',done:4,total:5,pace:'Ahead'},completedTopics:7},
 {id:'dash-10a',name:'10A Math',year:10,students:studentNames.slice(0,24),teacher:'Sarah Mitchell',avatar:3,tasks:tasks('10a',0,3,0),history:true,focus:null,completedTopics:4},
 {id:'dash-10b',name:'10B Math',year:10,students:studentNames.slice(0,23),teacher:'Sarah Mitchell',avatar:4,tasks:tasks('10b',0,2,0),history:true,focus:{topic:topics[4],end:'',done:1,total:5,pace:'On track'},completedTopics:3},
 {id:'dash-10c',name:'10C Math',year:10,students:studentNames.slice(0,22),teacher:'Sarah Mitchell',avatar:5,tasks:[],history:true,focus:{topic:topics[5],end:'',done:5,total:5,pace:'On track'},completedTopics:8},
 {id:'dash-8a',name:'8A Math',year:8,students:[],teacher:'Sarah Mitchell',avatar:0,tasks:[],history:false,focus:null,completedTopics:0},
 {id:'dash-8b',name:'8B Math',year:8,students:studentNames.slice(0,24),teacher:'Sarah Mitchell',avatar:1,tasks:[],history:false,focus:null,completedTopics:0},
 {id:'dash-school',name:'9A Math',year:9,students:studentNames.slice(0,26),teacher:'John Smith',avatar:2,tasks:tasks('9a',1,2,1),history:true,focus:{topic:topics[4],end:'',done:2,total:5,pace:'On track'},completedTopics:4}
]}
export function inBucket(t:DemoTask,b:Bucket){return b==='All'||b==='Recent'&&t.completed&&t.dueIn>=-7||b==='Active'&&!t.completed||b==='Due soon'&&!t.completed&&t.dueIn<=2}
export function featured(c:DashboardClass):{kind:'empty'|'first'|'focus'|'reward'|'idle'|'task';task?:DemoTask}{if(!c.students.length)return {kind:'empty'};if(!c.history&&!c.tasks.length)return {kind:'first'};const eligible=c.tasks.filter(t=>!t.dismissed);const urgent=eligible.find(t=>inBucket(t,'Due soon'));if(urgent)return {kind:'task',task:urgent};const recent=eligible.find(t=>inBucket(t,'Recent'));if(recent)return {kind:'task',task:recent};if(!c.focus)return {kind:'focus'};if(c.celebrate)return {kind:'reward'};const active=eligible.find(t=>!t.completed);return active?{kind:'task',task:active}:{kind:c.tasks.some(t=>!t.completed)?'reward':'idle'}}
export function loadDashboard():DashboardClass[]{try{const value=JSON.parse(localStorage.getItem('dashboard-classes-v1')||'null');return Array.isArray(value)&&value.length&&value.every(c=>Array.isArray(c.tasks)&&Array.isArray(c.students))?value:seedDashboard()}catch{return seedDashboard()}}
export function saveDashboard(value:DashboardClass[]){try{localStorage.setItem('dashboard-classes-v1',JSON.stringify(value))}catch{/* Session remains usable without storage. */}}
