import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const code=ts.transpileModule(fs.readFileSync(new URL('./model.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {seedDashboard,inBucket,featured,topics}=await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
const classes=seedDashboard();
assert.equal(topics.length,16);
const get=id=>classes.find(c=>c.id===`dash-${id}`);
assert.equal(featured(get('8a')).kind,'empty');
assert.equal(featured(get('8b')).kind,'first');
assert.equal(featured(get('10a')).kind,'focus');
assert.equal(featured(get('10c')).kind,'idle');
const urgent=get('7c');
assert.equal(featured(urgent).task.completed,false);
assert.equal(urgent.tasks.filter(t=>inBucket(t,'Due soon')).length,1);
assert.equal(urgent.tasks.filter(t=>inBucket(t,'Active')).length,2);
const recent=get('7b'), first=featured(recent).task;
const dismissed={...recent,tasks:recent.tasks.map(t=>({...t,dismissed:t.id===first.id}))};
assert.notEqual(featured(dismissed).task.id,first.id);
assert.equal(dismissed.tasks.filter(t=>inBucket(t,'Recent')).length,3);
assert.equal(inBucket({...first,dueIn:-8},'Recent'),false);
assert.equal(inBucket({...first,dueIn:-8},'All'),true);
for(const c of classes)for(const t of c.tasks)assert.ok(t.participation<=c.students.length);
console.log('Dashboard scenarios, urgent priority, dismissal/count consistency, and recent cutoff passed.');
