import { adaptiveRows, adaptiveDates } from '../test-controls/adaptive-data';
import type { AdaptiveStage } from '../test-controls/adaptive-data';
import { customDemoRows, scorecardResult, questions, response } from '../test-controls/report-data';
import { demoRows, NOW } from '../test-controls/model';
import type { DashboardClass } from './model';
export function progressiveClass(stage:AdaptiveStage):DashboardClass {
 const adaptive=adaptiveRows(stage),custom=customDemoRows(demoRows(stage));
 const tasks=[{id:'linear-equations-custom',title:'Linear equations custom task',type:'Custom task',rows:custom},{id:'linear-equations-adaptive',title:'Linear equations adaptive task',type:'Adaptive task',rows:adaptive}];
 return {id:'class-progressive-results',name:'Year 8 — Progressive results',year:8,avatar:0,teacher:'Sarah Mitchell (you)',students:[...new Set([...custom,...adaptive].map(s=>s.name))],history:true,focus:null,completedTopics:0,tasks:tasks.map(t=>({id:t.id,title:t.title,type:t.type,completed:stage==='After expiry',dueIn:stage==='Before due date'?1:-2,assignedCount:t.rows.length,participation:t.rows.filter(s=>s.progress>0).length,result:t.type==='Adaptive task'?null:Math.round(t.rows.reduce((n,s)=>n+(scorecardResult(s,NOW).percent??0),0)/t.rows.length),progress:Math.round(t.rows.reduce((n,s)=>n+('required' in s?Number(s.required)/12*100:s.progress),0)/t.rows.length),minutes:Math.round(t.rows.reduce((n,s)=>n+(s.timeSpent??0),0)/t.rows.length),startDate:(t.type==='Adaptive task'?adaptiveDates.start:t.rows[0].start).slice(0,10),dueDate:(t.type==='Adaptive task'?adaptiveDates.due:t.rows[0].due).slice(0,10),expiryDate:(t.type==='Adaptive task'?adaptiveDates.expiry:t.rows[0].expires??t.rows[0].due).slice(0,10)}))};
}
export function progressiveStudentStatus(taskId:string,name:string,stage:AdaptiveStage,grades=false){const adaptive=taskId==='linear-equations-adaptive';const row=(adaptive?adaptiveRows(stage):customDemoRows(demoRows(stage))).find(s=>s.name===name);if(!row)return 'Not assigned';if(grades){if(adaptive)return 'Mastery in report';const result=scorecardResult(row,NOW).percent;return result===null?'—':`${result}%`}return row.progress===0?'Not started':(row.status==='Completed'||('required' in row?Number(row.required)===12:row.progress>=100))?'Completed':stage==='After expiry'?'Closed':'In progress'}
export function progressiveActivity(name:string,stage:AdaptiveStage){const rows=[...customDemoRows(demoRows(stage)),...adaptiveRows(stage)].filter(s=>s.name===name);const answered=rows.reduce((n,s)=>n+('answered' in s?Number(s.answered):scorecardResult(s,NOW).answered),0);const correct=rows.reduce((n,s)=>n+questions.filter(q=>response(s,q).outcome==='Correct').length,0);return {questions:answered,accuracy:answered?Math.round(correct/answered*100):null,minutes:rows.reduce((n,s)=>n+(s.timeSpent??0),0),skills:adaptiveRows(stage).find(s=>s.name===name)?.skillCurrent.filter(v=>v>=4).length??null};}
