import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const compile=name=>ts.transpileModule(fs.readFileSync(new URL(name,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const url=s=>`data:text/javascript;base64,${Buffer.from(s).toString('base64')}`;
const {presetFilters,matchesTask,taskStatus,parseTaskFilters,relativeDate}=await import(url(compile('./task-list-model.ts')));
const {seedDashboard,inBucket}=await import(url(compile('./model.ts')));
const base={id:'test',title:'Fractions',type:'Custom task',completed:false,dueIn:0,participation:0,result:null};
const fixtures=[-8,-7,-1,0,1,2,3].flatMap(dueIn=>[false,true].map(completed=>({...base,dueIn,completed})));
for(const preset of ['All','Recent','Due soon','Active'])for(const task of fixtures)assert.equal(matchesTask(task,presetFilters(preset)),inBucket(task,preset),`${preset} due ${task.dueIn} closed ${task.completed}`);
assert.deepEqual(presetFilters('Recent').statuses,['In extension','Closed']);
assert.equal(presetFilters('Due soon').date,'Next 2 days');
assert.equal(taskStatus({...base,dueIn:-1}),'In extension');
assert.equal(matchesTask(base,{...presetFilters(),types:['Test']}),false);
assert.equal(matchesTask(base,{...presetFilters(),assigned:'Individual students'}),false);
assert.equal(matchesTask({...base,assignedTo:'Individual students'},{...presetFilters(),assigned:'Individual students'}),true);
assert.equal(matchesTask(base,{...presetFilters(),date:'Custom',from:relativeDate(1),to:relativeDate(3)}),false);
assert.equal(matchesTask({...base,dueIn:2},{...presetFilters(),date:'Custom',from:relativeDate(1),to:relativeDate(3)}),true);
assert.deepEqual(parseTaskFilters(JSON.stringify(presetFilters('Recent'))),presetFilters('Recent'));
assert.equal(parseTaskFilters('{broken'),undefined);
assert.equal(parseTaskFilters('{}'),undefined);
for(const c of seedDashboard())for(const preset of ['Recent','Due soon','Active'])assert.equal(c.tasks.filter(t=>matchesTask(t,presetFilters(preset))).length,c.tasks.filter(t=>inBucket(t,preset)).length);
console.log('Preset/count consistency, date boundaries, extension status, intersecting filters and URL state tests passed.');
