import { Link } from 'react-router-dom';
// Add new explorations here, in the order they should appear in the hub.
const prototypes=[{title:'Topic Readiness Check-in',path:'/prototypes/topic-readiness-check-in',description:'Explore two class data stories, readiness evidence and student scorecards.'},{title:'Dashboard explorations',path:'/prototypes/dashboards',description:'Compare the default My classes dashboard with the Today lesson-briefing exploration.'},{title:'Progressive results',path:'/prototypes/progressive-results',description:'Explore results as students work through Custom tasks. Adaptive tasks are coming later.'},{title:'Test controls',path:'/classes/class-test-controls/tasks/linear-equations-test',description:'Explore four task-report layouts, including start, pause, resume, restart and reassignment for groups and individual students.'}];
export default function Prototypes(){return <div className="prototype-page"><h1>Prototypes</h1><p>A place to explore and share ideas for the teacher experience.</p><div className="prototype-list">{[...prototypes].reverse().map(p=><Link className="prototype-card" to={p.path} key={p.path}><div><h2>{p.title}</h2><p>{p.description}</p></div><span>Open prototype →</span></Link>)}</div><footer>More prototypes will be added here as we explore.</footer></div>}

export function ProgressiveResults(){return <div className="prototype-page"><Link to="/prototypes">← Prototypes</Link><h1>Progressive results</h1><p>Explore results before the due date, during the extension window, and after expiry.</p><div className="prototype-list"><Link className="prototype-card" to="/classes/class-progressive-results/tasks/linear-equations-custom"><div><h2>Custom task</h2><p>Live results, student scorecards, question responses and marks.</p></div><span>Open prototype →</span></Link><Link className="prototype-card" to="/classes/class-progressive-results/tasks/linear-equations-adaptive"><div><h2>Adaptive task</h2><p>Progress, mastery, skills and student scorecards across all three stages.</p></div><span>Open prototype →</span></Link></div></div>}

export function DashboardPrototypes(){return <div className="prototype-page"><Link to="/prototypes">← Prototypes</Link><h1>Dashboard explorations</h1><p>Choose a dashboard direction. My classes is the default; Today preserves the earlier lesson-briefing exploration.</p><div className="prototype-list"><Link className="prototype-card" to="/dashboard"><div><h2>My classes · Default</h2><p>The staging design with varied class scenarios, task summaries, topic focus, and contextual actions.</p></div><span>Open dashboard →</span></Link><Link className="prototype-card" to="/prototypes/dashboards/today"><div><h2>Today · Exploration</h2><p>The earlier before, during, and after-class concept, including the Milo briefing and Overview alternative.</p></div><span>Open prototype →</span></Link></div></div>}

export function TopicReadinessPrototypes(){return <div className="prototype-page"><Link to="/prototypes">← Prototypes</Link><h1>Topic Readiness Check-in</h1><p>Explore two class profiles. Both include Detailed and Simplified layouts, Task snapshot and Latest evidence.</p><div className="prototype-list">{[{id:'a',title:'Building prerequisite foundations',description:'A class with widespread prerequisite gaps. Explore targeted support, limited evidence and strong task results that can mask low readiness.'},{id:'b',title:'Mixed readiness, stronger foundations',description:'A class with more established skills. Compare students ready before starting, remaining prerequisite gaps and growth after the check-in.'}].map(s=><Link key={s.id} className="prototype-card" to={`/classes/class-${s.id}/tasks/task-class-${s.id}-1/report`}><div><h2>{s.title}</h2><p>{s.description}</p></div><span>Open prototype →</span></Link>)}</div></div>}
