import { Link, useLocation } from 'react-router-dom';
import './PortalNavigation.css';
const asset='/assets/navigation/';
function NavIcon({name}:{name:string}){return <span aria-hidden="true" className="portal-icon" style={{maskImage:`url(${asset}${name}.svg)`}}/>}
export default function PortalNavigation({collapsed,onToggle}:{collapsed:boolean;onToggle:()=>void}){
 const {pathname}=useLocation();
 const items=[['/dashboard','Dashboard','home'],['/classes','Classes','classes'],['/students','Students','students'],['/templates','Templates','templates'],['/textbook','Textbook','textbook'],['/skills','Skills','skills'],['/prototypes','Prototypes','templates']];
 return <aside className={`portal-navigation ${collapsed?'is-collapsed':''}`} aria-label="Teacher portal"><div className="portal-top"><Link to="/dashboard" aria-label="Mathspace dashboard"><img className="portal-logo" src={`${asset}logo.svg`} alt="Mathspace"/></Link><Link to="/tasks/create" className="portal-assign" title="Assign task"><NavIcon name="add"/><span className="portal-label">Assign task</span></Link></div><nav aria-label="Main navigation">{items.map(([path,label,icon])=>{const active=pathname.startsWith(path)||(path==='/dashboard'&&pathname==='/')||(path==='/prototypes'&&pathname==='/test-controls');return <Link key={path} to={path} title={collapsed?label:undefined} aria-label={label} aria-current={active?'page':undefined} className={`portal-nav-link ${active?'is-active':''}`}><NavIcon name={icon}/><span className="portal-label">{label}</span></Link>})}<Link className="portal-search" to="/textbook" title="Search"><NavIcon name="search"/><span className="portal-label">Search</span></Link></nav><div className="portal-secondary"><Link className="portal-updates" to="/notifications" title="Updates"><NavIcon name="updates"/><span className="portal-label">Updates</span><span className="portal-new"><NavIcon name="new"/></span></Link><Link className="portal-support" to="/support" title="Live support"><NavIcon name="support"/><span className="portal-label">Live support</span></Link><Link className="portal-account" to="/profile" title="Account"><img src={`${asset}avatar.png`} alt=""/><span className="portal-label">Account</span></Link><button className="portal-collapse" onClick={onToggle} aria-expanded={!collapsed} aria-label={collapsed?'Expand navigation':'Collapse navigation'} title={collapsed?'Expand navigation':'Collapse navigation'}><NavIcon name="collapse"/><span className="portal-label">Collapse</span></button></div></aside>
}
