import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const source=ts.transpileModule(fs.readFileSync(new URL('./model.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {seed,NOW,applyAction,eligible,demoRows,tickAttempts,attemptPhase}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const opts={policy:'automatic',due:'2026-09-29T15:00',start:'2026-09-29T09:00',fresh:false,minutes:60,group:'New sitting'};
const ids=seed.map(s=>s.id);
const paused=applyAction(seed,ids,'Pause',opts,NOW);
assert.equal(paused.filter(s=>s.status==='Paused').length,11);assert.deepEqual(paused[4],seed[4]);assert.equal(eligible(seed[4],'Pause'),false);
const resumed=applyAction(paused,ids,'Resume',opts,NOW+600000);
assert.equal(resumed[0].remaining,seed[0].remaining);assert.equal(new Date(resumed[0].due)-new Date(seed[0].due),600000);assert.equal(resumed[6].status,'Scheduled');assert.equal(resumed[6].due,seed[6].due);assert.equal(resumed[10].due,seed[10].due);
const reassigned=applyAction(seed,[1,5],'Reassign',{...opts,fresh:true},NOW);
assert.equal(reassigned.length,14);assert.deepEqual(reassigned.slice(0,12),seed);assert.equal(reassigned[12].progress,0);assert.equal(reassigned[12].version,2);assert.equal(new Set(reassigned.map(s=>s.id)).size,14);
const restart=applyAction(seed,[1],'Restart',opts,NOW);assert.equal(restart[0].progress,seed[0].progress);assert.equal(restart[0].remaining,3600);
const fresh=applyAction(seed,[1],'Restart',{...opts,fresh:true},NOW);assert.equal(fresh[0].progress,0);assert.equal(fresh[0].version,2);
const reschedule=applyAction(seed,[1],'Reschedule',opts,NOW);assert.equal(reschedule[0].status,'Scheduled');assert.equal(reschedule[0].remaining,seed[0].remaining);
assert.equal(applyAction(seed,[7],'Start now',opts,NOW)[6].status,'In progress');assert.equal(applyAction(seed,[10],'Resume',{...opts,policy:'close'},NOW)[9].status,'Completed');
console.log('Passed all control-state checks.');

const mixed=demoRows();
assert.deepEqual([...new Set(mixed.map(s=>s.group))],['Group 1','Group 2']);
assert.ok(mixed.some(s=>attemptPhase(s,NOW)==='Expired'));
assert.ok(mixed.some(s=>attemptPhase(s,NOW)==='Closed'));
assert.ok(mixed.some(s=>attemptPhase(s,NOW)==='Before due date'));
assert.ok(mixed.some(s=>attemptPhase(s,NOW)==='After due date'));
for(const scenario of ['After expiry','Closed'])assert.ok(demoRows(scenario).every(s=>s.status==='Completed'));
const active={...mixed[3],status:'In progress',mode:'Scheduled',remaining:1};
assert.equal(tickAttempts([active],NOW)[0].status,'Completed');
assert.equal(tickAttempts([{...active,status:'Paused'}],NOW)[0].remaining,1);
const newAttempt=applyAction(mixed,[1],'Reassign',{...opts,fresh:true},NOW).at(-1);
assert.equal(newAttempt.closedAt,undefined);
assert.ok(new Date(newAttempt.expires)>new Date(newAttempt.due));
console.log('Lifecycle fixtures, expiry, clock and reassignment checks passed.');
