import { Children, createContext, useContext, useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { StudentAvatar } from './StudentAvatar';
import './table-display.css';
const labels: Record<string,string> = {status:'Status',remaining:'Remaining',controls:'Test controls',progress:'Progress',mastery:'Subtopic mastery',answered:'Questions answered',results:'Result',marks:'Mark',questions:'Question breakdown',time:'Time spent',group:'Task group',due:'Due date',expires:'Expiry date',participation:'Participation',average:'Average result',correct:'Correct',partial:'Partial',incorrect:'Incorrect',unanswered:'Not started',difficulty:'Difficulty',subproblems:'Subproblems',available:'Available marks',grade:'Grade',skill:'Skill'};
const formats = ['First name Last name','Last name, First name','First initial. Last name','First name Last initial.'];
type Settings = {order:string[];hidden:string[];avatars:boolean;format:number};
const defaults = ():Settings => ({order:Object.keys(labels),hidden:[],avatars:true,format:0});
const Context = createContext({settings:defaults(),save:(_value:Settings)=>{},names:[] as string[]});
export function TableDisplayProvider({taskType,names,children}:{taskType:string;names:string[];children:ReactNode}) {
 const key=`report-display-v1-${taskType}`;
 const [settings,setSettings]=useState<Settings>(()=>{try {const s=JSON.parse(localStorage.getItem(key)||'null');if(!s)return defaults();return {order:[...new Set([...s.order.filter((id:string)=>id in labels),...Object.keys(labels)])] as string[],hidden:s.hidden.filter((id:string)=>id in labels),avatars:s.avatars!==false,format:[0,1,2,3].includes(s.format)?s.format:0};}catch{return defaults();}});
 return <Context.Provider value={{settings,names,save:value=>{setSettings(value);try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Preferences remain usable for this session. */}}}}>{children}</Context.Provider>;
}
function formatName(name:string,format:number){const parts=name.trim().split(/\s+/),first=parts.slice(0,-1).join(' ')||name,last=parts.length>1?parts.at(-1)!:'';return !last?name:format===1?`${last}, ${first}`:format===2?`${first[0]}. ${last}`:format===3?`${first} ${last[0]}.`:name;}
export function DisplayName({name}:{name:string}) {const {settings,names}=useContext(Context);const short=formatName(name,settings.format);const collision=names.some(n=>n!==name&&formatName(n,settings.format)===short);return <span className="td-name" tabIndex={short!==name&&!collision?0:undefined} title={name} aria-label={name}>{collision?name:short}</span>}
export function DisplayAvatar({name}:{name:string}) {const {settings}=useContext(Context);return settings.avatars?<StudentAvatar name={name}/>:null}
export function DisplayRow({ids,children,className}:{ids:string[];children:ReactNode;className?:string}) {
 const {settings}=useContext(Context),cells=Children.toArray(children);
 const pairs=ids.map((id,index)=>({id,cell:cells[index]}));
 const fixedStart=pairs.filter(p=>p.id==='identity');
 const configurable=pairs.filter(p=>p.id in labels&&!settings.hidden.includes(p.id)).sort((a,b)=>settings.order.indexOf(a.id)-settings.order.indexOf(b.id));
 const fixedEnd=pairs.filter(p=>p.id!=='identity'&&!(p.id in labels));
 return <tr className={className}>{[...fixedStart,...configurable,...fixedEnd].map(p=><Cell key={p.id}>{p.cell}</Cell>)}</tr>;
}
function Cell({children}:{children:ReactNode}){return children}
export function DisplayPanel({columns,marks=false,students=true}:{columns:string[];marks?:boolean;students?:boolean}) {
 const {settings,save}=useContext(Context),[draft,setDraft]=useState(settings),[open,setOpen]=useState(false),[drag,setDrag]=useState<string|null>(null),[announcement,setAnnouncement]=useState('');
 const [dropTarget,setDropTarget]=useState<{id:string;after:boolean}|null>(null);
 const clearDrag=()=>{setDrag(null);setDropTarget(null)};
 const root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null);
 const close=()=>{clearDrag();setOpen(false);trigger.current?.focus()};
 useEffect(()=>{if(!open)return;panel.current?.focus();const down=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',down);return()=>document.removeEventListener('pointerdown',down)},[open]);
 const ordered=draft.order.filter(id=>columns.includes(id));
 const move=(id:string,target:string,after=false)=>{if(id===target)return;setDraft(d=>{const order=[...d.order];order.splice(order.indexOf(id),1);order.splice(order.indexOf(target)+(after?1:0),0,id);return {...d,order}});setAnnouncement(`${labels[id]} moved`)};
 return <div className="td-display" ref={root}><button ref={trigger} aria-haspopup="dialog" aria-expanded={open} onClick={()=>{if(open)close();else{setDraft(settings);setOpen(true)}}}><i className="td-display-icon" aria-hidden="true"/>Display</button>{open&&<div className="td-panel" ref={panel} style={{position:'fixed',top:Math.max(12,Math.min((trigger.current?.getBoundingClientRect().bottom??0)+8,window.innerHeight-Math.min(680,window.innerHeight-24)-12)),right:Math.max(12,window.innerWidth-(trigger.current?.getBoundingClientRect().right??window.innerWidth)),maxHeight:'min(680px, calc(100vh - 24px))'}} role="dialog" aria-label="Table display" tabIndex={-1} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close()}if(e.key==='Tab'){const items=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><header><strong>Table display</strong><button className="tc-icon-button tc-close-button td-close" aria-label="Close display settings" onClick={close}><i aria-hidden="true"/></button></header><div className="td-body"><p>Remembered across {students?'student and report':'report'} tables for this task type.</p><h3>Columns</h3><small>{marks?'Student and question marks stay fixed.':'Drag to reorder, or use the arrow buttons.'}</small><div className="td-columns" onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDropTarget(null)}}>{ordered.map((id,index)=><div className={`td-column ${drag===id?'td-dragging':''} ${dropTarget?.id===id?dropTarget.after?'td-drop-after':'td-drop-before':''}`} key={id} draggable={ordered.length>1}
 onDragStart={e=>{if((e.target as HTMLElement).closest('button,input')){e.preventDefault();return}const rect=e.currentTarget.getBoundingClientRect();e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',id);e.dataTransfer.setDragImage(e.currentTarget,Math.max(0,e.clientX-rect.left),Math.max(0,e.clientY-rect.top));setDrag(id)}}
 onDragEnd={clearDrag}
 onDragOver={e=>{if(!drag)return;e.preventDefault();e.dataTransfer.dropEffect='move';const rect=e.currentTarget.getBoundingClientRect();setDropTarget(drag===id?null:{id,after:e.clientY>rect.top+rect.height/2});const list=e.currentTarget.parentElement;if(list){const bounds=list.getBoundingClientRect();if(e.clientY<bounds.top+28)list.scrollTop-=10;else if(e.clientY>bounds.bottom-28)list.scrollTop+=10}}}
 onDrop={e=>{e.preventDefault();if(drag&&dropTarget)move(drag,dropTarget.id,dropTarget.after);clearDrag()}}><span className="td-handle" aria-hidden="true">⠿</span><label><input type="checkbox" checked={!draft.hidden.includes(id)} onChange={e=>setDraft(d=>({...d,hidden:e.target.checked?d.hidden.filter(v=>v!==id):[...d.hidden,id]}))}/>{labels[id]}</label><button aria-label={`Move ${labels[id]} up`} disabled={index===0} onClick={()=>move(id,ordered[index-1])}>↑</button><button aria-label={`Move ${labels[id]} down`} disabled={index===ordered.length-1} onClick={()=>{const next=ordered[index+1];move(next,id)}}>↓</button></div>)}</div>{students&&<section className="td-students"><h3>Student display</h3><label><input type="checkbox" checked={draft.avatars} onChange={e=>setDraft({...draft,avatars:e.target.checked})}/> Show avatars</label><label className="td-format">Name format<select value={draft.format} onChange={e=>setDraft({...draft,format:Number(e.target.value)})}>{formats.map((f,i)=><option key={f} value={i}>{f}</option>)}</select></label><div className="td-preview">{draft.avatars&&<StudentAvatar name="Amelia Chen"/>}<span>{formatName('Amelia Chen',draft.format)}</span></div></section>}</div><span className="td-sr" role="status">{announcement}</span><footer><button className="tc-text" onClick={()=>setDraft(defaults())}>Reset to default</button><div><button className="td-cancel" onClick={close}>Cancel</button><button className="tc-primary" onClick={()=>{save(draft);close()}}>Apply</button></div></footer></div>}</div>;
}
